version: '2'
services:
    db:
      image: postgres:latest
      env_file: docker-compose.env
    web:
      build: .
      command: ./docker-web-entrypoint
      env_file: docker-compose.env
      volumes:
        - .:/WebsiteISJ
      ports:
        - "8000:8000"
      links:
        - db:db
